name: gps_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6 
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  google_sign_in: ^5.4.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mainbg.jpg
    - assets/images/appicon.png
    
