name: gps_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6 
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  firebase_storage: ^12.4.5
  google_sign_in: ^5.4.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.4.0
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  geolocator: ^9.0.2
  geocoding: ^4.0.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/mainbg.jpg
    - assets/icons/appicon1.svg
    - assets/icons/appiconblk.svg
    - assets/icons/appiconwht.svg
    - assets/icons/motor.svg
    - assets/icons/google_icon.svg
    - assets/icons/motor.png
    - assets/fonts/

  fonts:
    - family: PlusJakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
