// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ1-waNq7Vc09dxi-qECAJOHYh2ZQOHOQ',
    appId: '1:309512527573:web:076b83d1ea0b66346c4c5c',
    messagingSenderId: '309512527573',
    projectId: 'gps-app-6712c',
    authDomain: 'gps-app-6712c.firebaseapp.com',
    storageBucket: 'gps-app-6712c.firebasestorage.app',
    measurementId: 'G-1QW2C9ZCR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwnp9iOwhIhIVpDHBvJRhFy7Hleft1NE8',
    appId: '1:309512527573:android:d9db07c5fab3f6bc6c4c5c',
    messagingSenderId: '309512527573',
    projectId: 'gps-app-6712c',
    storageBucket: 'gps-app-6712c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHVMMxt0xEB1ovKPpPyY7elzEnpw5D274',
    appId: '1:309512527573:ios:58960081936000236c4c5c',
    messagingSenderId: '309512527573',
    projectId: 'gps-app-6712c',
    storageBucket: 'gps-app-6712c.firebasestorage.app',
    iosBundleId: 'com.example.gpsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHVMMxt0xEB1ovKPpPyY7elzEnpw5D274',
    appId: '1:309512527573:ios:58960081936000236c4c5c',
    messagingSenderId: '309512527573',
    projectId: 'gps-app-6712c',
    storageBucket: 'gps-app-6712c.firebasestorage.app',
    iosBundleId: 'com.example.gpsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ1-waNq7Vc09dxi-qECAJOHYh2ZQOHOQ',
    appId: '1:309512527573:web:338c1d479509e98e6c4c5c',
    messagingSenderId: '309512527573',
    projectId: 'gps-app-6712c',
    authDomain: 'gps-app-6712c.firebaseapp.com',
    storageBucket: 'gps-app-6712c.firebasestorage.app',
    measurementId: 'G-NEPECDCCX7',
  );
}
