// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCprGyIVbsc-Yv3zGvhPSpH0uqiX3OVcbc',
    appId: '1:1025991041896:web:60caae73384a8fdc502cdd',
    messagingSenderId: '1025991041896',
    projectId: 'gps-project-a5c9a',
    authDomain: 'gps-project-a5c9a.firebaseapp.com',
    databaseURL:
        'https://gps-project-a5c9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-project-a5c9a.firebasestorage.app',
    measurementId: 'G-L7KF4C3QXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrq9LlADChQHZ3K8f0Je5ZfMACNo8DDp8',
    appId: '1:1025991041896:android:a1fa7840e74527eb502cdd',
    messagingSenderId: '1025991041896',
    projectId: 'gps-project-a5c9a',
    databaseURL:
        'https://gps-project-a5c9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-project-a5c9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbTQNQxiZ8LeRoSZmTKerOZL5u83MpD68',
    appId: '1:1025991041896:ios:e42edeecab41a87e502cdd',
    messagingSenderId: '1025991041896',
    projectId: 'gps-project-a5c9a',
    databaseURL:
        'https://gps-project-a5c9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-project-a5c9a.firebasestorage.app',
    iosBundleId: 'com.example.gpsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbTQNQxiZ8LeRoSZmTKerOZL5u83MpD68',
    appId: '1:1025991041896:ios:e42edeecab41a87e502cdd',
    messagingSenderId: '1025991041896',
    projectId: 'gps-project-a5c9a',
    databaseURL:
        'https://gps-project-a5c9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-project-a5c9a.firebasestorage.app',
    iosBundleId: 'com.example.gpsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCprGyIVbsc-Yv3zGvhPSpH0uqiX3OVcbc',
    appId: '1:1025991041896:web:0e9e27c2f7196107502cdd',
    messagingSenderId: '1025991041896',
    projectId: 'gps-project-a5c9a',
    authDomain: 'gps-project-a5c9a.firebaseapp.com',
    databaseURL:
        'https://gps-project-a5c9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-project-a5c9a.firebasestorage.app',
    measurementId: 'G-K71RL8QTHP',
  );
}
